"""empty message

Revision ID: 63d91fedc97a
Revises: 67a7610c6406
Create Date: 2020-02-05 09:41:06.947433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d91fedc97a'
down_revision = '67a7610c6406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('version', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'cameras', 'versions', ['version'], ['id'])
    op.add_column('companies', sa.Column('secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'secret')
    #op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_column('cameras', 'version')
    # ### end Alembic commands ###
